spring:
  application:
    name: ProductManager
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductsDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: kafka:9092 
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
       spring:
         json:
           trusted:
             packages: com.example.ProductManager.event
      
      